services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
   # healthcheck:
   #   test: ["CMD-SHELL", "pg_isready -U admin -d social"]
   #   interval: 10s
    #  timeout: 5s
   #   retries: 5

volumes:
  db-data: